import { SurveySection } from '@/lib/generatePrompt';

export function formatGoogleForms(sections: SurveySection[]): string {
    const items: Array<Record<string, unknown>> = [];
    
    sections.forEach((section) => {
        // Add section heading as a page break/description item
        if (section.questions.length > 0) {
            items.push({
                title: section.title,
                pageBreakItem: {}
            });
        }
        
        // Add all questions in this section
        section.questions.forEach(q => {
            let questionItem: Record<string, unknown> = {};

            switch (q.type) {
                case 'SINGLE_CHOICE':
                    questionItem = {
                        question: {
                            required: true,
                            choiceQuestion: {
                                type: 'RADIO',
                                options: [
                                    ...(q.options?.map(opt => ({ value: opt })) || []),
                                    ...(q.config?.allow_other ? [{ isOther: true }] : [])
                                ]
                            }
                        }
                    };
                    break;
                case 'MULTI_CHOICE':
                    questionItem = {
                        question: {
                            required: true,
                            choiceQuestion: {
                                type: 'CHECKBOX',
                                options: [
                                    ...(q.options?.map(opt => ({ value: opt })) || []),
                                    ...(q.config?.allow_other ? [{ isOther: true }] : [])
                                ]
                            }
                        }
                    };
                    break;
                case 'LIKERT_SCALE':
                    const scaleLabels = Array.isArray(q.config?.scale_labels) ? q.config.scale_labels : null;
                    questionItem = {
                        question: {
                            required: true,
                            scaleQuestion: {
                                low: q.config?.scale_min || 1,
                                high: q.config?.scale_max || 5,
                                lowLabel: scaleLabels?.[0],
                                highLabel: scaleLabels?.[scaleLabels.length - 1]
                            }
                        }
                    };
                    break;
                case 'OPEN_TEXT':
                    questionItem = {
                        question: {
                            required: true,
                            textQuestion: { paragraph: q.config?.input_size !== 'short' }
                        }
                    };
                    break;
                // RANK_ORDER and NUMERIC_INPUT don't map perfectly to simple Google Forms JSON schema 
                // without more complex grid/validation structures, so we map to reasonable defaults.
                case 'RANK_ORDER':
                    questionItem = {
                        description: "Please rank the following options:",
                        questionGroupItem: {
                            questions: q.options?.map(opt => ({
                                required: true,
                                rowQuestion: { title: opt }
                            }))
                        }
                    };
                    break;
                case 'NUMERIC_INPUT':
                    questionItem = {
                        question: {
                            required: true,
                            textQuestion: { paragraph: false } // Short answer validated as number manually in UI
                        }
                    };
                    break;
            }

            items.push({
                title: q.text,
                ...questionItem
            });
        });
    });
    
    const googleFormsData = {
        title: "Generated Survey",
        description: "Survey generated by SurveySmith",
        items
    };

    return JSON.stringify(googleFormsData, null, 2);
}
